# config-h.awk - convert config.h in a Scheme program.
# $Id$
BEGIN {
  print ";; generated by config-h.awk";
}
$1 == "#define" {
  if (NF == 3) {
    print "(define " $2 " '" $3 ")";
  }
}
$2 == "#undef" {
  print "(define " $3 " #f)";
}
