# config-h.awk - convert config.h in a Scheme program.
# $Id$
BEGIN {
  print ";; generated by config-h.awk";
  "(LANG=C && date)" | getline date;
  print "(define date \"" date "\")";
  print "";
}
$1 == "#define" {
  if (NF == 3) {
    print "(define " $2 " '" $3 ")";
  } else {
    gsub(/\",  *\"/, "\" \"");
    printf "(define %s '\(", $2;
    for (i = 3; i <= NF; i++) {
      printf " %s", $i;
    }
    print "))";
  }
}
$2 == "#undef" {
  print "(define " $3 " #f)";
}
